#!/bin/sh
#

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

bin/message-generator message:generate message#commit --output=./.git/tmp-commit-msg
echo $(cat ./.git/tmp-commit-msg) > $1